<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Support\Str;
use App\Models\Registration;
use Illuminate\Http\Request;
use App\Mail\RegistrationMail;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class RegistrationController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Request $request)
    {
        //
        // dd($request->all());
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email',
            // 'password' => 'required|string|min:8|confirmed',
            'faculty' => 'required|string|max:255',
            'major_id' => 'required|integer|max:255',
            'photo' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            'role' => 'required|string|in:student,alumni',
        ]);
        // dd($request->all());
        $user = Auth::guard('sanctum')->user();
        if (!$user->hasRole('admin')) {
            return response()->json([
                'error' => 'You are not authorized to perform this action',
            ], 403);
        }
        $registration = new User();
        $registration->name = $request->name;
        $registration->email = $request->email;
        $autogeneratedPassword = Str::password(8);
        $registration->password = bcrypt($autogeneratedPassword);
        $registration->faculty = $request->faculty;
        $registration->role = $request->role;
        $registration->phone = $request->phone;
        $registration->enrollment_year = $request->enrollment_year;
        $registration->graduation_year = $request->graduation_year;
        $registration->bio = $request->bio;
        $registration->home_country = $request->home_country;
        $registration->job_title = $request->job_title;
        $registration->company = $request->company;
        $registration->position = $request->position;
        $registration->account_status = 'active';
        $registration->registration_date = now();
        $registration->major_id = $request->major_id;
        $registration->admin_id = $user->id;

        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $file->move(public_path('photos'), $filename);
            $registration->photo = $filename;
        }
        $registration->save();
        // Send email to the user with the autogenerated password
        // dd($registration);
        Mail::to($registration->email)->send(new RegistrationMail($registration, $autogeneratedPassword));
        return response()->json([
            'message' => 'Registration successful',
            'registration' => $registration,
        ], 201);

    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Registration $registration)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Registration $registration)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Registration $registration)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Registration $registration)
    {
        //
    }
}
